package com.example.springboot.bean;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;

import java.util.Date;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.USER_ID
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    @TableId(value = "USER_ID", type = IdType.AUTO)
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.USER_NAME
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.PASSWORD
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.TELEPHONE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.USER_ROLE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    private Integer userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.EMAIL
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.GENDER
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.IS_VIP
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    private Integer isVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.VIP_LEFT_DATE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    private Date vipLeftDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.USER_ID
     *
     * @return the value of userinfo.USER_ID
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.USER_ID
     *
     * @param userId the value for userinfo.USER_ID
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.USER_NAME
     *
     * @return the value of userinfo.USER_NAME
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.USER_NAME
     *
     * @param userName the value for userinfo.USER_NAME
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.PASSWORD
     *
     * @return the value of userinfo.PASSWORD
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.PASSWORD
     *
     * @param password the value for userinfo.PASSWORD
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.TELEPHONE
     *
     * @return the value of userinfo.TELEPHONE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.TELEPHONE
     *
     * @param telephone the value for userinfo.TELEPHONE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.USER_ROLE
     *
     * @return the value of userinfo.USER_ROLE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public Integer getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.USER_ROLE
     *
     * @param userRole the value for userinfo.USER_ROLE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setUserRole(Integer userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.EMAIL
     *
     * @return the value of userinfo.EMAIL
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.EMAIL
     *
     * @param email the value for userinfo.EMAIL
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.GENDER
     *
     * @return the value of userinfo.GENDER
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.GENDER
     *
     * @param gender the value for userinfo.GENDER
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.IS_VIP
     *
     * @return the value of userinfo.IS_VIP
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public Integer getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.IS_VIP
     *
     * @param isVip the value for userinfo.IS_VIP
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setIsVip(Integer isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.VIP_LEFT_DATE
     *
     * @return the value of userinfo.VIP_LEFT_DATE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public Date getVipLeftDate() {
        return vipLeftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.VIP_LEFT_DATE
     *
     * @param vipLeftDate the value for userinfo.VIP_LEFT_DATE
     *
     * @mbggenerated Sun Jun 30 20:58:15 CST 2019
     */
    public void setVipLeftDate(Date vipLeftDate) {
        this.vipLeftDate = vipLeftDate;
    }
}